### ISSUE TITLE
About Cuda Version

### ISSUE THREAD

**Issue by sabah150170** [uni-halle/gerbil#24]
Hi, 

I try to run gerbil via this command,
" ./gerbil -k 18 -l 1 -g SRR097732_1.fastq  /tmp output "

But I got an error like this,
"Error while searching for GPU's: CUDA driver version is insufficient for CUDA runtime version
Disabling GPU support.
unable to create output-file"

I check CUDA version
"nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130"

This looks up to date. Could you please help me how  I can solve this.

**Comment by srechner** [comment]
Which NVIDIA driver version do you use? You may test that with the command `nvidia-smi`.

**Comment by sabah150170** [comment]
Hi, I changed the cuda and boost version that I used so I fixed the issue. But  I have a different problem now. I am sharing the screen shot about the new problem,

![gerbil2](https://user-images.githubusercontent.com/43916858/231522712-45d4f1a6-94f0-4688-b1a0-697e118ff4e0.png)

Could you please help me how I can solve this.

**Comment by srechner** [comment]
There seem to be 2 errors. 

1. Gerbil is trying to write a temporary file to the root directory. Specify `/tmp/` as tempory directory (with / at the end). 
2. Gerbil still cannot find any GPU. Please give me the output of `nvidia-smi`.

**Comment by sabah150170** [comment]
Actually, I need to run the gerbil application in two different systems. In the first one, I am getting above error and the output of the command you asked like this,

![gerbil3](https://user-images.githubusercontent.com/43916858/232333562-9bb7704a-d377-4acc-a10a-8fef3e2dfde1.png)

------------------------------------------------------------------------------------------------------------------------------------
And in the second system, I got an error during the make and the error is this, 

![make_gerbil](https://user-images.githubusercontent.com/43916858/232333864-3dd4efed-b3ee-457e-8388-f18c648e8c22.png)

output of cmake is this,

![cmake_gerbil](https://user-images.githubusercontent.com/43916858/232333874-2723a611-51c1-480a-9526-d66199364380.png)

Thanks you.

**Comment by srechner** [comment]
As the output of nvidia-smi says, it seems that you don't have an NVIDIA driver installed. You need to install one.

In the second system , the cmake log seems fine but the make process fails due to missing dependencies of your boost library. I would suggest removing all boost libraries and rebuild boost from the souce code.
